name: actions
on:
  push:
jobs:
  debian-debootstrap:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        QEMU_VER: [v7.2.0-1]
        DOCKER_REPO: [docker.io/robbydyer/debian-debootstrap]
        VERSION: [buster, bullseye, bookworm]
        UNAME_ARCH: [x86_64, arm64, armel, armv7l ]
        include:
          - {ARCH: amd64,     QEMU_ARCH: x86_64,  UNAME_ARCH: x86_64}
          - {ARCH: arm64,     QEMU_ARCH: aarch64, UNAME_ARCH: arm64}
          - {ARCH: armel,     QEMU_ARCH: armeb,   UNAME_ARCH: armel}
          - {ARCH: armhf,     QEMU_ARCH: arm,     UNAME_ARCH: armv7l}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build
        run: |
          sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu jammy main universe'
          sudo apt-get update && sudo apt-get install -y qemu-user-static debootstrap
          ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -o ${{ matrix.UNAME_ARCH }}
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker push -a ${{ matrix.DOCKER_REPO }}
